### ISSUE TITLE
SCRIPT ERROR

### ISSUE THREAD

**Issue by balcer64** [jay-fivem/qb-core_logohud#1]
[38;5;98m[ script:core_logohud] > TriggerCallback (@qb-core/server/functions.lua:125)
[38;5;98m[ script:core_logohud] > handler (@qb-core/server/events.lua:116)
[38;5;98m[ script:core_logohud] SCRIPT ERROR: @core_logohud/server/main.lua:5: attempt to index a nil value (local 'xPlayer')
[38;5;98m[ script:core_logohud] > TriggerCallback (@qb-core/server/functions.lua:125)
[38;5;98m[ script:core_logohud] > handler (@qb-core/server/events.lua:116)
[38;5;98m[ script:core_logohud] SCRIPT ERROR: @core_logohud/server/main.lua:5: attempt to index a nil value (local 'xPlayer')
[38;5;98m[ script:core_logohud] > TriggerCallback (@qb-core/server/functions.lua:125)
[38;5;98m[ script:core_logohud] > handler (@qb-core/server/events.lua:116)
[38;5;98m[ script:core_logohud] SCRIPT ERROR: @core_logohud/server/main.lua:5: attempt to index a nil value (local 'xPlayer')
[38;5;98m[ script:core_logohud] > TriggerCallback (@qb-core/server/functions.lua:125)
[38;5;98m[ script:core_logohud] > handler (@qb-core/server/events.lua:116)
[38;5;98m[ script:core_logohud] SCRIPT ERROR: @core_logohud/server/main.lua:5: attempt to index a nil value (local 'xPlayer')
[38;5;98m[ script:core_logohud] > TriggerCallback (@qb-core/server/functions.lua:125)
[38;5;98m[ script:core_logohud] > handler (@qb-core/server/events.lua:116)
[38;5;98m[ script:core_logohud] SCRIPT ERROR: @core_logohud/server/main.lua:5: attempt to index a nil value (local 'xPlayer')
[38;5;98m[ script:core_logohud] > TriggerCallback (@qb-core/server/functions.lua:125)
[38;5;98m[ script:core_logohud] > handler (@qb-core/server/events.lua:116)
[38;5;98m[ script:core_logohud] SCRIPT ERROR: @core_logohud/server/main.lua:5: attempt to index a nil value (local 'xPlayer')
[38;5;98m[ script:core_logohud] > TriggerCallback (@qb-core/server/functions.lua:125)
[38;5;98m[ script:core_logohud] > handler (@qb-core/server/events.lua:116)
[38;5;98m[ script:core_logohud] SCRIPT ERROR: @core_logohud/server/main.lua:5: attempt to index a nil value (local 'xPlayer')
[38;5;98m[ script:core_logohud] > TriggerCallback (@qb-core/server/functions.lua:125)
[38;5;98m[ script:core_logohud] > handler (@qb-core/server/events.lua:116)
[38;5;98m[ script:core_logohud] SCRIPT ERROR: @core_logohud/server/main.lua:5: attempt to index a nil value (local 'xPlayer')
[38;5;98m[ script:core_logohud] > TriggerCallback (@qb-core/server/functions.lua:125)
[38;5;98m[ script:core_logohud] > handler (@qb-core/server/events.lua:116)

**Comment by merpindia** [comment]
i have fix
